name: Weekly LINE Push

on:
  schedule:
    - cron: '0 12 * * 5'  # 每週五晚上 8:00（台灣時間 UTC+8）
  workflow_dispatch:

permissions:
  contents: write  # 允許推送檔案

jobs:
  weekly_notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas requests line-bot-sdk

      - name: 產生 HTML 報表
        run: python stock_ex.py  # 這支腳本內部完成資料擷取+產生 docs/report.html

      - name: Commit and push HTML to GitHub Pages
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add reports/report.html
          git commit -m "自動產生最新報表 HTML" || echo "No changes to commit"
          git push

      - name: Send LINE message with GitHub Pages link
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        run: python send_line_message_ex.py
