name: Weekly LINE Push

on:
  schedule:
    - cron: '0 12 * * 5'  # 每週五晚上 8:00（台灣時間 UTC+8）
  workflow_dispatch:

permissions:
  contents: write  # 允許 GitHub Actions 有權限 push 檔案
  
jobs:
  weekly_notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests pandas openpyxl line-bot-sdk

      - name: Create reports directory
        run: mkdir -p reports

      - name: Run Python script
        run: python stock_ex.py

      - name: Rename Excel file (avoid Unicode issues)
        run: |
          if [ -f "reports/除權息資料排序結果.xlsx" ]; then
            mv "reports/除權息資料排序結果.xlsx" "reports/dividend_report.xlsx"
          fi

      - name: Check generated files
        run: ls -lh reports/

      - name: Commit and push Excel
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add reports/dividend_report.xlsx
          git commit -m "Update Excel on $(date '+%Y-%m-%d')" || echo "No changes to commit"
          git push

      - name: Send LINE message with file link
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        run: python send_line_message_ex.py
